#+OPTIONS: toc:nil H:10 tex:t author:nil
#+TITLE:
#+DATE:
#+STARTUP: odd hidestars indent
#+LaTeX_HEADER: \usepackage{mycv}
#+LaTeX_HEADER: \hypersetup{hidelinks}
#+LaTeX_CLASS_OPTIONS: [letterpaper]

\resheader{ Cameron Lopez }{  }{  }{  }{  }{  }

* Experience

*** Software Devloper - Oppenheimer Funds
***** 2018 - Current
Designed and built a distributed architecture for processing financial data

- Python, AWS(EBS, EC2 AutoScale, Aurora, ELB, Elasticache), Postgres, Groovy on Grails, SQL, Oracle DB, Jenkins

*** Founder - 8Reps Fitness
***** 2016 - Current
Designed and built a fitness platform to seamlessly connect users to gyms.

- React Native, Serverless, NodeJS, Express, GraphQL, Docker, iOS, Android, MongoDB

*** Software Developer III - Rackspace - VMWare
***** 2015 - Current
Lead dev team to iterative release cycle. Created an automated build system to configure bare metal hypervisors. Built self service vCenter storage metrics application; this resulted in an enhanced customer experience and reduced overhead by 1000+ hours of work.

- vCenter, Grails, Groovy, JS, RabbitMQ, Splunk

*** Software Developer in Test III - Rackspace - VMware
***** 2014 - 2015
Developed a testing service which led to a successful product launch. Mentored new developers and fostered documentation to effectively grow the team.

- vCloud Director, Python, Bottle, Docker, Neo4j, Redis, Celery, REST

*** Software Developer in Test - Rackspace - Openstack
***** 2012 - 2014
Developed a CI test framework which rapidly integrates changes to a OpenStack private cloud product and provides continuous stable releases to customers. Pushed product interests into OpenStack open-source projects to create a greater enterprise experience to customers.

- OpenStack, Python, Chef, Razor, Ansible, Jenkins, Red Hat Enterprise Linux

*** Workstudy Developer - The University of Texas at San Antonio Ambassadors
***** 2011 - 2012
Drove improvements by gathering and implementing requirements reducing overhead by 75%. Designed an application which created a self sustaining work management system. Provided content management as well as self service metrics eliminating the need for any technical role.

- Ruby on Rails, Heroku, Postgres, PHP, MySQL, JS

* Education

*** Georgia Institute of Technology - Atlanta, Georgia
***** 2016 - Current
M.S., Computer Science, Machine Learning

- Designed an Unscented Kalman Filter to localize and predict movement of objects using a neural network. Leveraged Python, opencv, numpy, and pybrain.

*** The University of Texas at San Antonio - San Antonio, TX
***** 2009 - 2012
B.S., Computer Science, Concentration in Software Engineering

- Built a Ruby on Rails social book application to provide recommendations and connections. Leveraged Google Book APIs, Heroku, and Postgres.

- Built a RESTful medical information system using PHP, and MySQL.

* Research
*** Undergraduate Research Group - Institute for Cyber Security
***** 2012
Cloud Computing Security, Virtualization

- Surveyed general virtualization technology, micro-virtualization, and cloud security.

* Specialties
  - Frameworks :: React, Express, Grails, Flask, Rails, Django, Relay, GraphQL
  - Software lifecycle :: Agile Automated build process: Jenkins, Travis-CI
  - Deployment automation and management :: Docker, Ansible, Chef, Razor
  - Version Control :: git, Github, mercurial
  - Virtualization :: AWS, Openstack, VMware, vCloud Director, vCenter, GCP, Azure
  - Database administration :: neo4j, mysql, postgres
  - Languages :: javascript, python, groovy, ruby, C, php
  - System administration :: Linux, RHEL
